include:
  - template: Terraform/Base.latest.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.latest.gitlab-ci.yml

parallel:
  matrix:
    - RESEARCH_GROUP:
      # - epistemopratique
      - reso-t

cache:
  key: "${RESEARCH_GROUP}"
  paths:
    - .terraform

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt

validate:
  extends: .terraform:validate

build:
  extends: 
    - .terraform:build
  environment:
    name: $RESEARCH_GROUP
    action: prepare
  resource_group: $RESEARCH_GROUP

deploy:
  extends: 
    - .terraform:deploy
  dependencies:
    - build
  environment:
    name: $RESEARCH_GROUP
    action: start
  resource_group: $RESEARCH_GROUP

destroy:
  extends:
    - .terraform:destroy
  dependencies:
    - deploy
  environment:
    name: $RESEARCH_GROUP
    action: stop  
  resource_group: $RESEARCH_GROUP

pages:
  stage: deploy
  image: python:3.10
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - sphinx-build docs public
  artifacts:
    paths: ['public']
  only:
    - main
