image: python:3.10

before_script:
  - pip install -r docs/requirements.txt

pages:
  stage: build
  script:
    - sphinx-build html docs public
  artifacts:
    paths: ['public']
#  only:
#    - main
